spring:
  datasource:
    url: jdbc:mariadb://pillin.cl84wsky80vr.ap-northeast-2.rds.amazonaws.com:3306/s10p12b101?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${db.username}
    password: ${db.password}
    hikari:
      maximum-pool-size: 5
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: false

  oauth:
    kakao:
      client-id: ${kakao.key}
      redirect-uri: "https://i10b101.p.ssafy.io/login/oauth2/kakao"
      grant_type: authorization_code

  mail:
    host: smtp.naver.com
    port: 465
    username: ${email.username}
    password: ${email.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

