// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4M36lJTHQQ5_v05ZCJae18A6nEW51dM0',
    appId: '1:1055153492019:web:2a8d9239654eb28f5bd346',
    messagingSenderId: '1055153492019',
    projectId: 'pillin-d420f',
    authDomain: 'pillin-d420f.firebaseapp.com',
    storageBucket: 'pillin-d420f.appspot.com',
    measurementId: 'G-5H97QKTDBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWwJqXgiQjQDI7QLgQ_LixXzZIEs5RTp0',
    appId: '1:1055153492019:android:4c982d79494320545bd346',
    messagingSenderId: '1055153492019',
    projectId: 'pillin-d420f',
    storageBucket: 'pillin-d420f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXhKCJrZTgVDLbocCI-RhR-pzokKiKtFs',
    appId: '1:1055153492019:ios:caf41df2e86467685bd346',
    messagingSenderId: '1055153492019',
    projectId: 'pillin-d420f',
    storageBucket: 'pillin-d420f.appspot.com',
    iosBundleId: 'com.example.yourpilling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXhKCJrZTgVDLbocCI-RhR-pzokKiKtFs',
    appId: '1:1055153492019:ios:e3db98809b00bb875bd346',
    messagingSenderId: '1055153492019',
    projectId: 'pillin-d420f',
    storageBucket: 'pillin-d420f.appspot.com',
    iosBundleId: 'com.example.yourpilling.RunnerTests',
  );
}
